### ISSUE TITLE
Example HTML to properly use the table splite hack

### ISSUE THREAD

**Issue by gogades** [tonnyavery/JSUtils#2]
I'm trying to make use of the table split hack to manage a fairly large table and it's making quite a mess of it :-/

I was wondering if you would have a sample HTML page which renders a table across several pages properly so that I could see the best way it is done.

Much appreciated.

**Comment by tonnyavery** [comment]
The only thing I have left from that project are template examples that were used to generate relatively large html's.
I have added a couple .erb files to the wkhtmltopdfTableSplitHack folder of the repo, please use them as a reference.

I will try to come up with a more actual usage example.

**Comment by gogades** [comment]
Thanks, I will take a look !

**Comment by gogades** [comment]
As it turns out, what I was missing was some of the css like the hidden class. Once I got that in place the rendering improved significantly.

**Comment by tonnyavery** [comment]
Glad template helped you to figure that out:)
